#%RAML 1.0 NamedExample
{
    "Name":"vinod",
    "LastName":"kumar",
    "PhoneNo":"1234564789",
    "EmailId":"vinod@gmail.com",
    "ItemsCost": 1200.00,
    
    "BillingAddress":{
        "StreetAddress":"1032 West side dr",
        "City":"Gaithersburg",
        "State":"MD",
        "pincode":"20878"
    },
    "PaymentDetails":{
        "PaymentType":"Visa",
        "transactionNo":"asdhvuh23n390uaufa"
    },
    "Tax":23.65,
    "TotalCost":1223.65 
    
}