#%RAML 1.0 Library
types:
  cartItem: !include ../dataTypes/cartDatatype.json

traits:
  transacitonHeader: !include ../traits/commonHeaderTrait.raml
  errorCodes: !include ../traits/commonErrorTrait.raml
